apiVersion: apps/v1
kind: Deployment
metadata: 
  name: spring-petclinic-deploy
spec:
  selector:
    matchLabels:
      app: spring-petclinic
  template: 
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers: 
      -
        image: secobau/spring-petclinic:latest
        name: spring-petclinic-container
        ports:
        -
          containerPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: spring-petclinic-netpol
spec:
  ingress:
  -
    ports:
    -
      port: 8080
  podSelector:
    matchLabels:
      app: spring-petclinic
---
apiVersion: v1
kind: Service
metadata: 
  name: spring-petclinic-svc
spec:
  ports:
  -
    nodePort: 30000
    port: 80
    targetPort: 8080
  selector:
    app: spring-petclinic
  type: NodePort
