name: CI-minikube
on: 
  #push:
    #branches: [main]
jobs:
  minikube:
    env:
      mode: minikube
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@v2
    -
      run: |

        #set -x

        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
        sudo dpkg -i minikube_latest_amd64.deb

        project=$(basename $GITHUB_REPOSITORY)

        compose=etc/docker/$mode/$project.yaml
        date=$(date +%s)

        sed -i s/latest/$mode-$date/ $compose
        docker build -t $GITHUB_REPOSITORY:$mode-$date --no-cache .

        free -h
        minikube start && minikube kubectl -- apply -f $compose
        free -h

        while true
          do
            sleep 1
            minikube kubectl -- get deploy
            minikube kubectl -- get deploy | grep '\([0-9]\)/\1' && break
          done
